# Generated by Django 3.2.19 on 2023-06-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='username',
        ),
    ]
