# Generated by Django 3.2.19 on 2023-06-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0002_remove_studio_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='last_name',
        ),
    ]
