# Generated by Django 3.2.19 on 2023-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0005_confirmationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationcode',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='action_type',
            field=models.CharField(choices=[('reset', 'reset'), ('signup', 'signup')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='confirmationcode',
            constraint=models.UniqueConstraint(fields=('email', 'action_type'), name='unique pair'),
        ),
    ]
