# Generated by Django 3.2.19 on 2023-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0006_auto_20230704_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
