# Generated by Django 3.2.19 on 2023-07-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0008_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='full_name',
            new_name='name',
        ),
    ]
