# Generated by Django 3.2.19 on 2023-07-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0009_rename_full_name_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='full_name',
        ),
    ]
