# Generated by Django 4.2.3 on 2023-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
