# Generated by Django 3.2.19 on 2023-07-16 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import customer.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('school_subject', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='person_staff_photo/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff',
                                             to='studio.school')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_index', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(
                    message='Номер класса должен содержать число 1-11 и заглавную букву через пробел',
                    regex='^(?:[1-9]|1[0-1]) [А-Я]$')])),
                ('customer_first_name', models.CharField(max_length=150)),
                ('customer_last_name', models.CharField(max_length=150)),
                ('customer_middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True, validators=[
                    django.core.validators.RegexValidator(
                        message='Номер телефона должен состоять из 10 цифр и начинаться с 9', regex='^9\\d{9}$')])),
                ('albums_count', models.IntegerField()),
                ('passcode', models.IntegerField(default=customer.utils.generate_random_passcode)),
                ('status', models.CharField(
                    choices=[('created', 'Создан'), ('portraits_uploading', 'Загрузка портретов'),
                             ('portraits_uploaded', 'Портреты загружены'),
                             ('portraits_processing', 'Обработка портретов'),
                             ('portraits_processed', 'Портреты обработаны'), ('layout', 'Верстка'),
                             ('agreement', 'Согласование'), ('printing', 'Печать'), ('completed', 'Завершен'),
                             ('rejected', 'Отменен')], default='created', max_length=25)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='order', to='studio.school')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order',
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
