# Generated by Django 4.2.3 on 2023-08-18 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
