# Generated by Django 4.2.3 on 2023-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('s3_url', models.CharField(max_length=255, unique=True)),
                ('faces_count', models.IntegerField()),
            ],
        ),
    ]
