# Generated by Django 4.2.3 on 2023-08-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0002_school_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='order',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order',
                                    to='common.studio'),
        ),
        migrations.AlterField(
            model_name='school',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school',
                                    to='common.studio'),
        ),
    ]
