# Generated by Django 4.2.3 on 2023-09-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0003_alter_personstudent_name_alter_personstudent_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.TextField()),
                ('portrait_student_single', models.TextField()),
                ('portrait_student_multi', models.TextField()),
                ('portrait_staff_multi', models.TextField()),
                ('gallery', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.TextField()),
                ('portrait_student_single', models.TextField()),
                ('portrait_student_multi', models.TextField()),
                ('portrait_staff_multi', models.TextField()),
                ('gallery', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
