# Generated by Django 4.2.3 on 2023-09-07 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0004_template_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template',
                                    to='common.studio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[
                django.core.validators.RegexValidator(
                    message='Номер телефона должен состоять из 10 цифр и начинаться с 9', regex='^9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='personstudent',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personstudent',
            name='vector',
            field=models.JSONField(),
        ),
    ]
