# Generated by Django 3.2.19 on 2023-07-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_client', '0002_order_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('school_subject', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='person_staff_photo/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff', to='customer_client.school')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer_client.school'),
        ),
    ]
