# Generated by Django 3.2.19 on 2023-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_client', '0003_auto_20230706_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personstaff',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id']},
        ),
    ]
