# Generated by Django 3.2.19 on 2023-07-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_client', '0008_school'),
        ('customer_client', '0004_auto_20230706_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='studio_client.school'),
        ),
        migrations.AlterField(
            model_name='personstaff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff', to='studio_client.school'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
