# Generated by Django 3.2.19 on 2023-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0005_auto_20230710_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('portraits_uploading', 'Загрузка портретов'),
                                            ('portraits_uploaded', 'Портреты загружены'),
                                            ('portraits_processing', 'Обработка портретов'),
                                            ('portraits_processed', 'Портреты обработаны'), ('layout', 'Верстка'),
                                            ('agreement', 'Согласование'), ('printing', 'Печать'),
                                            ('completed', 'Завершен'), ('rejected', 'Отменен')], default='Создан',
                                   max_length=25),
        ),
    ]
