# Generated by Django 3.2.19 on 2023-07-13 14:19

import django.core.validators
from django.db import migrations, models

import customer_client.utils


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
        migrations.AddField(
            model_name='order',
            name='passcode',
            field=models.CharField(default=customer_client.utils.generate_random_passcode, max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='class_index',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(
                message='Номер класса должен содержать число 1-11 и заглавную букву через пробел',
                regex='^(?:[1-9]|1[0-1]) [А-Я]$')]),
        ),
    ]
