# Generated by Django 3.2.19 on 2023-07-14 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0007_auto_20230713_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(
                message='Номер телефона должен состоять из 10 цифр и начинаться с 9', regex='^9\\d{9}$')]),
        ),
    ]
