# Generated by Django 3.2.19 on 2023-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0008_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Загрузка портретов', 'Загрузка портретов'),
                                            ('Портреты загружены', 'Портреты загружены'),
                                            ('Обработка портретов', 'Обработка портретов'),
                                            ('Портреты обработаны', 'Портреты обработаны'), ('Верстка', 'Верстка'),
                                            ('Согласование', 'Согласование'), ('Печать', 'Печать'),
                                            ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Создан',
                                   max_length=25),
        ),
    ]
