# Generated by Django 3.2.19 on 2023-07-15 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(
                message='Номер телефона должен состоять из 10 цифр и начинаться с 9', regex='^9\\d{9}$')]),
        ),
    ]
