# Generated by Django 3.2.19 on 2023-07-15 13:04

from django.db import migrations, models

import customer_client.utils


class Migration(migrations.Migration):
    dependencies = [
        ('customer_client', '0010_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passcode',
            field=models.IntegerField(default=customer_client.utils.generate_random_passcode),
        ),
    ]
