# Generated by Django 4.2.3 on 2023-08-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vector', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_url', models.CharField(max_length=255, unique=True)),
                ('faces_count', models.IntegerField()),
                ('focus', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type',
                 models.CharField(blank=True, choices=[('staged', 'staged'), ('reportage', 'reportage')], max_length=10,
                                  null=True)),
                ('horizont', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoPersonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_fill_percent', models.IntegerField(blank=True, null=True)),
                ('blink', models.BooleanField(blank=True, null=True)),
                ('look_to_camera', models.BooleanField(blank=True, null=True)),
                ('person_student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.personstudent',
                                   verbose_name='person_student')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.photo',
                                            verbose_name='photo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='personstudent',
            name='main_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_photo',
                                    to='common.photo'),
        ),
        migrations.AddField(
            model_name='personstudent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.order'),
        ),
        migrations.AddField(
            model_name='personstudent',
            name='photos',
            field=models.ManyToManyField(related_name='photo', through='common.PhotoPersonStudent', to='common.photo',
                                         verbose_name='student photos'),
        ),
        migrations.AddConstraint(
            model_name='photopersonstudent',
            constraint=models.UniqueConstraint(fields=('photo', 'person_student'),
                                               name='unique pair for photo and person_student'),
        ),
    ]
